# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.5
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: williamdvp@hotmail.com
author_name: William Vasquez
cloud_provider: vercel
preset_name: production
project_name: frontend

